# Generated by Django 5.2 on 2026-01-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetups', '0002_delete_meetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('attendees', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
