# Generated by Django 5.2.8 on 2026-01-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_participant_meetup_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='organizer_mail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
