# Generated by Django 5.2.8 on 2026-04-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='articles', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Está activo?'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='marca',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del artículo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='stock',
            field=models.IntegerField(verbose_name='Cantidad en stock'),
        ),
    ]
