# Generated by Django 5.2.8 on 2026-04-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_articulos', '0002_alter_articulo_options_articulo_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='Imagen'),
        ),
    ]
