# Generated by Django 5.2 on 2026-01-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meetup',
        ),
    ]
